[build]
  command = "node scripts/run-migrations.js && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Disable auto-installed integrations that are causing build failures
[integrations]
  auto_install = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
