export const defaultFoodItems = [
  {
    name: 'Chicken Breast',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: '100g',
    isCustom: 0,
  },
  {
    name: 'Brown Rice',
    calories: 112,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    servingSize: '100g',
    isCustom: 0,
  },
  {
    name: 'Broccoli',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    servingSize: '100g',
    isCustom: 0,
  },
  {
    name: 'Banana',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    servingSize: '1 medium (118g)',
    isCustom: 0,
  },
  {
    name: 'Egg',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    servingSize: '2 large',
    isCustom: 0,
  },
  {
    name: 'Oatmeal',
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    servingSize: '100g',
    isCustom: 0,
  },
  {
    name: 'Salmon',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    servingSize: '100g',
    isCustom: 0,
  },
  {
    name: 'Greek Yogurt',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: '100g',
    isCustom: 0,
  },
]
